### PR TITLE
Fix a bug

### PR DESCRIPTION
**Pull request by raxonpc**

### CODE REVIEW

**Comment by B4mbus** [comment]
Hey raxon.
I'm really pleased that you are concerned by the safety and correctness of my fizz buzz implementation.
I reviewed your commit and I'm not quite sure why you think a missing `return 0;` at the end of the `main` function is a bug.
If you could please reply with an explanation we could maybe settle on closing this pull request.

Thank you.

**Comment by raxonpc** [comment]
Hello B4mbus.
Referring to chapter 3.6.1 paragraph 5 of the c++ standard, the return 0; statement is added implicitly at the end of the main function. However, my teacher Mirexalt Zealand would always consider my program "incomplete" without the "return 0;" line, that led to me failing the class. So it can be considered a bug

**Comment by wzslr321** [comment]
hello raxon
si si torro, +1

**Comment by B4mbus** [comment]
@raxonpc 
After a thorougful consideration of your arguments I'm pressed to agree and merge your PR. 
I'm greatful that you decided to sacrifice some of your valuable time to contribute to that great project.

@wzslr321 si torro

**Comment by wzslr321** [comment]
Very good decision @B4mbus 
Your project is 🚀  to the 🌚 now. 
This shit bussin

**Pull request merged**
